### ISSUE TITLE
error inserting my own files into genome grist for target download_matching_genomes

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/genome-grist#77] opened 2021-05-15 00:19 UTC
I'm not sure what error I'm making to cause this error message.

directory structure:
```
$ ls *
conf.yml  README.sh

genbank:
gather_vita_vars_gtdb_shared_assemblies.x.genbank.gather.csv

genbank_genomes:
```

conf file:
```
sample:
- gather_vita_vars_gtdb_shared_assemblies
outdir: .
metagenome_trim_memory: 1e9
```

command:
```
genome-grist run conf.yml download_matching_genomes
```

Error:
```
genome-grist run conf.yml download_matching_genomes
sample: ['gather_vita_vars_gtdb_shared_assemblies']
outdir: .
Building DAG of jobs...
InputFunctionException in line 144 of /home/tereiter/miniconda3/envs/grist/lib/python3.8/site-packages/genome_grist/conf/Snakefile:
Error:
  WorkflowError:
    Missing wildcard values for sample
Wildcards:

Traceback:
  File "/home/tereiter/miniconda3/envs/grist/lib/python3.8/site-packages/genome_grist/conf/Snakefile", line 131, in __call__
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/miniconda3/envs/grist/lib/python3.8/site-packages/genome_grist/conf/Snakefile', '-j', '1', '--use-conda', 'download_matching_genomes', '--configfile', '/home/tereiter/miniconda3/envs/grist/lib/python3.8/site-packages/genome_grist/conf/defaults.conf', '/home/tereiter/miniconda3/envs/grist/lib/python3.8/site-packages/genome_grist/conf/system.conf', 'conf.yml']' returned non-zero exit status 1.
```

head of the gather file i'm using (I did read a bunch of gather files into R and then write this out, so theres NAs, but I don't think they're the problem):

```
intersect_bp,f_orig_query,f_match,f_unique_to_query,f_unique_weighted,average_abund,median_abund,std_abund,name,filename,md5,f_match_orig,unique_intersect_bp,gathe
868000,0.01065658301821932,0.1523876404494382,0.01065658301821932,0.01065658301821932,NA,NA,NA,"GCA_000210075.1 Bacteroides xylanisolvens XB1A strain=XB1A, ASM2100
58000,7.120758237980651e-4,2.918004085205719e-4,2.2098904876491677e-4,2.2098904876491677e-4,NA,NA,NA,"GCA_000256725.2 Toxoplasma gondii TgCatPRC2 strain=TgCatPRC2,
106000,0.0013013799538378432,0.004314477468839885,2.2098904876491677e-4,2.2098904876491677e-4,NA,NA,NA,"GCA_000285855.2 Ruminococcus sp. JC304, ASM28585v2",/group/
394000,0.004837204734076512,0.2008324661810614,0.0047389873790698814,0.0047389873790698814,NA,NA,NA,"GCA_000431575.1 Firmicutes bacterium CAG:83, MGS83",/group/ctb
134000,0.001645140696361047,0.030209140201394268,9.576192113146393e-4,9.576192113146393e-4,NA,NA,NA,"GCA_000432135.1 Firmicutes bacterium CAG:124, MGS124",/group/c
20000,2.455433875165742e-4,0.009478672985781991,2.455433875165742e-4,2.455433875165742e-4,NA,NA,NA,"GCA_000432155.1 Eubacterium sp. CAG:274, MGS274",/group/ctbrown
100000,0.001227716937582871,0.030973451327433628,6.875214850464077e-4,6.875214850464077e-4,NA,NA,NA,"GCA_000432375.1 Firmicutes bacterium CAG:103, MGS103",/group/c
96000,0.001178608260079556,0.0519774011299435,0.0011294995825762413,0.0011294995825762413,NA,NA,NA,"GCA_000432435.1 Eubacterium sp. CAG:180, MGS180",/group/ctbrown
62000,7.6118450130138e-4,0.01794071762870515,5.647497912881207e-4,5.647497912881207e-4,NA,NA,NA,"GCA_000434635.1 Firmicutes bacterium CAG:110, MGS110",/group/ctbro
22000,2.700977262682316e-4,0.015068493150684932,2.700977262682316e-4,2.700977262682316e-4,NA,NA,NA,"GCA_000435175.1 Clostridium sp. CAG:245, MGS245",/group/ctbrown
540000,0.0066296714629475026,0.209992193598751,0.006605117124195845,0.006605117124195845,NA,NA,NA,"GCA_000435395.1 Firmicutes bacterium CAG:94, MGS94",/group/ctbro
82000,0.0010067278888179541,0.04411764705882353,8.839561950596671e-4,8.839561950596671e-4,NA,NA,NA,"GCA_000435555.1 Firmicutes bacterium CAG:176, MGS176",/group/ct
```

**Comment by ctb** [comment] 2021-05-15 00:35
on a first skim, it looks good to me. odd...

**Comment by ctb** [comment] 2021-05-15 14:35
I can reproduce the error. I am not 100% sure of what the problem is, sorry!

**Comment by taylorreiter** [comment] 2021-05-15 17:28
Annoyingly, this works to get the genome info files...

```
genome-grist run conf.yml --until download_matching_genomes_info
```

**Comment by taylorreiter** [comment] 2021-05-15 17:48
lol and 
```
genome-grist run conf.yml --until make_sgc_conf
```

downloads the genomes so...that's nice.

**Comment by ctb** [comment] 2022-01-12 14:23
fixed in https://github.com/dib-lab/genome-grist/pull/125

**Closed by ctb** 2022-01-12 14:23 UTC
